### ISSUE TITLE
[BUG]: western_goods_tasks_act_3.script:450: attempt to index local 'sender_2' (a nil value)

### ISSUE THREAD

**Issue by Annoneq** [nltp-ashes/Western-Goods#62] opened 2024-03-06 22:58 UTC
### Description

when picking up documents from dead SSU squad game get crash

### Addon version

v2.5.0

### Game version

1.5.2

### Log output

Expression    : <no expression>
Function      : CScriptEngine::lua_pcall_failed
File          : D:\a\xray-monolith\xray-monolith\src\xrServerEntities\script_engine.cpp
Line          : 262
Description   : fatal error
Arguments     : 
 1 : [Lua] ....5.1.2\gamedata\scripts\western_goods_tasks_act_3.script(450) : 

LUA error: ....5.1.2\gamedata\scripts\western_goods_tasks_act_3.script:450: attempt to index local 'sender_2' (a nil value)

Check log for details

stack trace:

### Contact

Annoneq

### Confirmation

- [X] Yes, I have.

**Comment by Annoneq** [comment] 2024-03-06 22:58
[xray_annoneq.log](https://github.com/nltp-ashes/Western-Goods/files/14516587/xray_annoneq.log)

**Comment by nltp-ashes** [comment] 2024-04-21 10:06
Hello @Annoneq,

Sorry for taking a while to answer you.

Reading your log, it seems the task NPC has somehow disappeared (or was killed, but this is technically not possible).

I cannot explain what happened. I was suspecting `grok_dynamic_despawner.script` to be the cause of this problem, but you do not seem to be using it. If you have used it in the past, it could still be the problem.

You can try spawning the NPC again with the [debug menu's Object Spawner](https://igigog.github.io/anomaly-modding-book/modding-tools/in-game-editors/object-spawner.html) :
- Select the "Spawn at smart terrain" mode;
- In the "Spawn by section" field, type `stalker_danylo_chernenko_squad`;
- In the "Select level" field, select `jupiter/`;
- In the "Select smart" field, select `jup_a6`;
- Then click spawn.

After this, you should be able to proceed with the task normally.

**Comment by nltp-ashes** [comment] 2024-07-16 19:03
Hello @Annoneq,

Given you are not answering, and [someone has found](https://www.moddb.com/mods/stalker-anomaly/addons/western-goods/page/12#8807865) that this solution does indeed fix the problem, I am closing this issue.

**Closed by nltp-ashes** 2024-07-16 19:03 UTC
Labels: bug, question
