### ISSUE TITLE
[BUG]: could not create model dynamics\artefacts\artefact_electra_blue_hud, section artefact_hud_blue

### ISSUE THREAD

**Issue by Moons12345** [nltp-ashes/Western-Goods#79] opened 2024-06-12 23:22 UTC
### Description

Hello! I have a bug that I can't fix. Could you help me? It happens to me when equipping the lighter (the game crashes)

### Addon version

v2.6.0

### Game version

1.5.2

### Game execution log

FATAL ERROR
 
[error]Expression    : visual
[error]Function      : attachable_hud_item::load
[error]File          : D:\a\xray-monolith\xray-monolith\src\xrGame\player_hud.cpp
[error]Line          : 425
[error]Description   : could not create model dynamics\artefacts\artefact_electra_blue_hud, section artefact_hud_blue
 

stack trace:

### Confirmation

- [X] Yes, I have read the instructions and have all the pre-requisites installed.

**Comment by nltp-ashes** [comment] 2024-07-21 19:55
Hello @Moons12345,

Without further information from you, I am closing this issue.

If you do believe this issue is caused by my addon (although I doubt it is), please re-open the issue.

**Closed by nltp-ashes** 2024-07-21 19:55 UTC
Labels: bug, question
