### ISSUE TITLE
[CHANGE]: Currencies - Williams "Ashes" Heades has duplicate dialog for bartering

### ISSUE THREAD

**Issue by Rambito1** [nltp-ashes/Western-Goods#86] opened 2024-08-23 02:03 UTC
### Description

We talked about this before, William have 2 barter dialogs _(barter and exchange)_ that do the same thing, I think because of the the changes in the latest barter mod version.
In the trade menu, he offer a PDA for zero cost, it cost no Ru, $ or €
![08-22-24_19-25-09_(pripyat)](https://github.com/user-attachments/assets/6724c8b0-9c91-4025-989f-03c1a5dfca1a)
![08-22-24_19-25-31_(pripyat)](https://github.com/user-attachments/assets/118cceab-3d8d-43bb-a2d4-2adc2235ea58)

### Addon version

v3.0.0

### Game version

1.5.2

### Game execution log

No log for this because it causes no crashes...no?

### Confirmation

- [X] Yes, I have read the instructions and have all the pre-requisites installed.

**Comment by nltp-ashes** [comment] 2024-08-23 09:15
Hello @Rambito1,

Thank you for submitting this issue.

First of, you are describing two different problems. It would be better to make an issue for each of them. That being said, I am pretty sure the PDA gets added by another addon, and I am not sure what I can do about it.

As for the duplicated line of dialog, you are correct, this is not normal. This happens because historically, the [Anomaly Barter UI Framework](https://github.com/ahuyn/anomaly-barter) by [ahuyn](https://github.com/ahuyn) used to add a button in the trade menu of the NPC in order to start the barter UI. I did not like this and decided to externally alter its behavior, by making it a line of dialog instead. Either ahuyn had the same idea or maybe he was inspired by what I did, but you are right, it seems this is no longer necessary. As such, I will be removing the line of dialog I added.

I will update this issue as development progresses.

**Comment by Minolta50** [comment] 2024-08-27 12:09
same issue
![ss_tabishev arts_08-27-24_17-05-15_(pripyat)](https://github.com/user-attachments/assets/14cb781d-0584-4dda-9b8d-1a7d6a49fc61)

**Comment by nltp-ashes** [comment] 2024-08-27 12:50
Hello @Minolta50,

Thank you for your comment. I was able to replicate the issue after @Rambito1's message, so I can confirm that this will be fixed.

Matter of facts, work has already started on fixing this problem. I have [contributed to the Anomaly Barter UI Framework](https://github.com/ahuyn/anomaly-barter/pull/5), and I added the code I need in order to make it work just like it was before.

I also started work on Western Goods' side. Technically, this work is even complete. All I need to do now is test my code to make sure it works. After this, the fix will be complete and ready for release in `v3.1.0`.

**Comment by nltp-ashes** [comment] 2024-08-28 20:31
Hello @Rambito1 & @Minolta50,

I am glad to confirm that, using the `25-08-2024` version of the [Barter UI Framework](https://github.com/ahuyn/anomaly-barter/releases/tag/latest), this issue has been resolved.

![image](https://github.com/user-attachments/assets/ae257665-4ef3-41cd-911d-be4cab5dce0b)

![image](https://github.com/user-attachments/assets/3913c124-87b0-4056-a32c-331f099af88e)

The fix will be available when `v3.1.0` will release.

**Closed by nltp-ashes** 2024-08-28 20:31 UTC
Labels: suggestion
